[game]
    [caption]
        display_caption="reversi"
    [display_size]
        width=1200
        height=630

    [background_color]
        red=0
        green=0
        blue=0
        alpha=0

    [fps]
        time=30
